### ISSUE TITLE
Include awk_cmd

### ISSUE THREAD

**Issue by brickyyyy** [ManchesterBioinference/Scasat#1]
I found a missing line in your code while trying to reproduce it. You might want to add it :) 
`softwares = {   
    'awk_cmd': awk_cmd_path,
    'bowtie2': bowtie_path,
    'macs2': macs2_path,
    'bdg2bw': bdg2bw_path,
    'samtools': samtools_path,
    'picard': picard_path,
    'intersectBed': intersectBed_path,
    'MarkDuplicate': MarkDuplicate_path,
    'trimmomatic': Trimmomatic_path,
    'fastqc': fastqc_path,
    'Trimmomatic_Adapter': Trimmomatic_Adapter
}`

**Comment by galib36** [comment]
Thank you @brickyyyy . Have corrected the code.
