### ISSUE TITLE
Package for jaccard?

### ISSUE THREAD

**Issue by brickyyyy** [ManchesterBioinference/Scasat#3]
What package are you using for calculating the Jaccard dissimilarity? It would be useful to include a list of packages that the user needs to install before running the pipeline. 
`    SingleCell.Binary.Jaccard <- jaccard(as.matrix(SingleCell.Binary))
`

**Comment by galib36** [comment]
Thank you again for the message. I used `prabclus`. I din't mention the package names separately because there is a cell that tries to install all the required packages through `pacman`. I think I would add it in the documentation.

**Comment by brickyyyy** [comment]
Thank you too for reaching out so fast! :) :+1: :1st_place_medal:
