### ISSUE TITLE
Error in import(mergedPeakFile) : could not find function "import"

### ISSUE THREAD

**Issue by mvinyard** [ManchesterBioinference/Scasat#4]
I am having trouble getting your code to run the import function to import a file. Import is not included in base R or any of the dependencies you mention to be required for Scasat - is there a package that I should load first in order for this function to run?

**Comment by galib36** [comment]
Could you please mention the notebook name where you are having this issue?

**Comment by mvinyard** [comment]
We are using "ScAsAT_functions_Buenrostro_All_Bam_Together"

**Comment by galib36** [comment]
In this file the import function for R is from ChIPpeakAnno.

**Comment by mvinyard** [comment]
We installed and loaded this package, however we are still running into the following error (screenshotted). It's also worth noting that I opened an R notebook within Jupyter to avoid complication. 
![Screen Shot 2019-04-16 at 5 03 11 PM](https://user-images.githubusercontent.com/47393421/56243921-b372f980-6069-11e9-8472-0e2c492b34c4.png)

**Comment by mvinyard** [comment]
I also tried loading rtracklayer to get the following error: 
![Screen Shot 2019-04-16 at 5 06 14 PM](https://user-images.githubusercontent.com/47393421/56244062-fd5bdf80-6069-11e9-85bf-7b59f03839ec.png)

**Comment by galib36** [comment]
Did `ChIPpeakAnno` or `rtracklayer` gave any error during loading? Also, could you please let me know the version of this two packages?

**Comment by mvinyard** [comment]
They gave no error during loading, except the warnings for which functions would be blocked from other packages, which I assumed to be ok. 

Versions:
ChIPpeakAnno: bioconductor-chippeakanno 3.16.0
rtracklayer: bioconductor-rtracklayer  1.42.1

**Comment by galib36** [comment]
Can you please try with the following two files? 
https://www.dropbox.com/s/11gxzomo5t0yomg/All_Human_Bam_NoTrimmo_NoShift.csv?dl=0
https://www.dropbox.com/s/mnw359iqcd9zqam/mergedPeaks.bed?dl=0

**Comment by mvinyard** [comment]
Hi, I was able to try this with your files and I got it to work. However, I think a main point of confusion I am having is discerning the difference between the narrow peak and mergedpeak file. Currently, we simply renamed merge peak to narrow peak to get this to run -  I’m not sure if that’s the appropriate way.

**Comment by mvinyard** [comment]
Hi again, I am still having some trouble. It seems the bed file I am working with (pictured below) for the "merged peaks" file has some more info than the bed file you provided. Also, I am curious as to why I needed to rename even your merged peaks file with a '_peaks.narrowPeak' extension name?

Like I mentioned above I am still having trouble getting this to run with my bed file - any help would be appreciated. 

![Screen Shot 2019-04-22 at 12 16 56 PM](https://user-images.githubusercontent.com/47393421/56510686-8787c600-64f8-11e9-8e73-61c9b526c3bc.png)

**Comment by galib36** [comment]
Thank you again for your input on the tool. The current format needs the bed file to be in Bed3 with an additional fourth column as score. However, you can modify the function to include more columns. Additionally, the file needs to be tab separated.

**Comment by galib36** [comment]
For the file extension, I have kept the peak file name ending with `_peaks.narrowPeak` as this is the default peak file extension output from `MACS2`.

**Comment by mvinyard** [comment]
Thanks for your comments. How is this fourth column, the 'score' generated? What does this score refer to?

**Comment by galib36** [comment]
Thank you again for the question. The values of the 5th column in narrowPeak files are equal to the integer part of 9th column (-log10qvalue) multiplied by 10. int(-10*log10qvalue). I used `bedtool merge -c` command to merge the peak files where I asked to operate on column 5. For details you can have a look at the following documentation for `bedtools merge` command

https://bedtools.readthedocs.io/en/latest/content/tools/merge.html

**Comment by mvinyard** [comment]
Thank you for your help!
