### ISSUE TITLE
Error in calcEntropy: Error in base::table(...) : attempt to make a table with >= 2^31 elements

### ISSUE THREAD

**Issue by mvinyard** [ManchesterBioinference/Scasat#5]
Hi again,

Thanks for all of your help thus far. I have successfully and reproducibly generated my feature matrix from the peakAccessibility function. However I am getting the following error: 

`Error in base::table(...) : attempt to make a table with >= 2^31 elements`

Is there any further transformation of the matrix that needs to be done before inputting to calcEntropy?

<img width="696" alt="Screen Shot 2019-05-03 at 11 26 06 AM" src="https://user-images.githubusercontent.com/47393421/57147953-ab6bc700-6d96-11e9-9348-a0286d9be372.png">

Thanks again for all of your generous help!

**Comment by galib36** [comment]
Sorry for the late reply,  did you get it solved?

**Comment by mvinyard** [comment]
Yep, got it figured out, thanks!

**Comment by FARIDAblaq** [comment]
@mvinyard How did you figure it out? I'm stuck on the same error
<img width="1290" alt="Screenshot 2022-02-10 at 4 25 26 AM" src="https://user-images.githubusercontent.com/43499936/153336962-e10c8a35-61e0-4c18-b5e4-244e6c4e2939.png">

**Comment by mvinyard** [comment]
> @mvinyard How did you figure it out? I'm stuck on the same error

@FARIDAblaq I wish I wrote down what I did. Unfortunately, I don't really remember and don't have any record of it. I'll do some digging. If I find what I did, I'll report back.

**Comment by mvinyard** [comment]
> @mvinyard How did you figure it out? I'm stuck on the same error

@FARIDAblaq I believe this [notebook](https://nbviewer.org/github/pinellolab/scATAC-benchmarking/blob/master/Real_Data/Buenrostro_2018/run_methods/Scasat/Scasat_buenrostro2018.ipynb?flush_cache=true) contains everything I would have done. Unfortunately, I don't remember exactly how I solved this but hopefully the notebook helps.

**Comment by FARIDAblaq** [comment]
Thank you @mvinyard
